const profiles = [
  {
    id: 1,
    photo: "",
    name: "Pragati",
    age: "27 Yrs",
    height: "5 ft 2 in",
    language: "Tamil",
    religion: "Hindu",
    caste: "Nair",
    qualification: "MBBS",
    profession: "Doctor",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
  },
  {
    id: 2,
    photo: "",
    name: "Priyanka",
    age: "27 Yrs",
    height: "5 ft 2 in",
    language: "Tamil",
    religion: "Hindu",
    caste: "Nair",
    qualification: "MBBS",
    profession: "Doctor",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
  },
  {
    id: 3,
    photo: "",
    name: "Aiswarya",
    age: "27 Yrs",
    height: "5 ft 2 in",
    language: "Tamil",
    religion: "Hindu",
    caste: "Nair",
    qualification: "MBBS",
    profession: "Doctor",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
  },
  {
    id: 4,
    photo: "",
    name: "Sindhu",
    age: "27 Yrs",
    height: "5 ft 2 in",
    language: "Tamil",
    religion: "Hindu",
    caste: "Nair",
    qualification: "MBBS",
    profession: "Doctor",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
  },
  {
    id: 5,
    photo: "",
    name: "Meenakshi",
    age: "27 Yrs",
    height: "5 ft 2 in",
    language: "Tamil",
    religion: "Hindu",
    caste: "Nair",
    qualification: "MBBS",
    profession: "Doctor",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
  },
  {
    id: 6,
    photo: "",
    name: "Divya",
    age: "27 Yrs",
    height: "5 ft 2 in",
    language: "Tamil",
    religion: "Hindu",
    caste: "Nair",
    qualification: "MBBS",
    profession: "Doctor",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
  },
  {
    id: 7,
    photo: "",
    name: "Priya",
    age: "27 Yrs",
    height: "5 ft 2 in",
    language: "Tamil",
    religion: "Hindu",
    caste: "Nair",
    qualification: "MBBS",
    profession: "Doctor",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
  },
  {
    id: 8,
    photo: "",
    name: "Renuga",
    age: "27 Yrs",
    height: "5 ft 2 in",
    language: "Tamil",
    religion: "Hindu",
    caste: "Nair",
    qualification: "MBBS",
    profession: "Doctor",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
  },
  {
    id: 9,
    photo: "",
    name: "Nayantara",
    age: "27 Yrs",
    height: "5 ft 2 in",
    language: "Tamil",
    religion: "Hindu",
    caste: "Nair",
    qualification: "MBBS",
    profession: "Doctor",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
  },
  {
    id: 10,
    photo: "",
    name: "Trisha",
    age: "27 Yrs",
    height: "5 ft 2 in",
    language: "Tamil",
    religion: "Hindu",
    caste: "Nair",
    qualification: "MBBS",
    profession: "Doctor",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
  },
];
export default profiles;
